name: Auto-merge to main

on:
  push:
    branches:
      - [ feature/*, bugfix/* ]

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install git
        run: sudo apt-get update && sudo apt-get install -y git
      - name: Fetch updates
        run: git fetch origin
      - name: Merge to main
        run: |
          git config user.name "Nivin"
          git config user.email "getnivin@gmail.com"
          git merge origin main
        env:
          GITHUB_TOKEN: ${{ secrets.MULTITHREAD }}
